version: '3'
services:
  snapapp:
    build:
      context: .
      dockerfile: docker/snap.dev
    command: bash -c "stack build && stack exec app -fdevelopment" 
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    links:
      - db
  db:
    image: postgres:9.6.5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
