version: '3'
services:
  snapapp:
    build:
      context: .
      dockerfile: docker/snap.prod
    command: stack exec app -p 80 
    working_dir: /app
    ports:
      - 80:80
    links:
      - db
  db:
    image: postgres:9.6.5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  .cabal:
