resolver: lts-12.13
packages:
  - '.'
  - location:
      git: https://github.com:g-erson/snaplet-persistent
      commit: a72ef62f5
    extra-dep: true
extra-deps:
  - snap-loader-static-0.9.0.2
  - snap-loader-dynamic-0.10.0.4
flags: {}
extra-package-dbs: []
allow-different-user: true
