resolver: lts-11.20
extra-deps:
  - snap-loader-dynamic-1.0.0.0
  - snap-loader-static-1.0.0.0
  - snaplet-persistent-0.6.0
flags: {}
extra-package-dbs: []
allow-different-user: true
allow-newer: true
